Server:
  port: 9091
spring:
  application:
    name: API-GATEWAY
  cloud:
   gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/user/**
        - id: discovery-service
          uri: lb://DISCOVERY-SERVICE
          predicates:
            - Path=/api/v1/discovery-service/**
        - id: api-gateway
          uri: lb://API-GATEWAY
          predicates:
            - Path=/api/v1/api-gateway/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment-service/**
        - id: report-service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/api/v1/report-service/**
        - id: integration-service
          uri: lb://INTEGRATION-SERVICE
          predicates:
            - Path=/api/v1/integration-service/**

  spring.cloud.gateway:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

  logging:
    level:
      org.springframework.cloud.gateway: TRACE

#   dns:
#     cloudflare:
#       enabled: true
#     google:
#       enabled: true
#       order: 1
#       servers:
#         - 8.8.8.8
#         - 8.8.4.4
#
#     inet-utils:
#       ignoredInterfaces:
#         - eth0
#         - eth1
#         - eth2
#         - eth3
#       preferredNetworks:
#         - 192.168
#         - 10.0

#    inet-utils:
#      ignoredInterfaces:
#        - eth0
#        - eth1
#        - eth2
#        - eth3
#      preferredNetworks:
#        - 192.168
#        - 10.0
#        - 172.24
#        - 169.254

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoint:
    web:
      exposure:
        include: "prometheus,health,info"
        server:
          port: 8081
          logging:
            pattern:
              level: "%5p [${spring.application.name:},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-}]"



zipkin:
  base-url: http://localhost:9411/api/v2/spans
  sender:
    type: web
  enabled: true
  sampler:
    probability: 1.0
  messaging:
    enabled: true

