server:
  port: 8081
spring:
  application:
    name: MEMBER-SERVICE  # This is the name of the service
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/



  r2dbc:
    url: r2dbc:postgresql://localhost:5432/devpayflexdb?schema=member
    username: devpayflexuser
    password: devpayflexpass

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: member
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/devpayflexdb
    user: devpayflexuser
    password: devpayflexpass


#    data:
#      r2dbc:
#        repositories:
#          enabled: true # Enable R2DBC repositories
#    flyway:
#      baseline-description: Baseline migration
#      baseline-on-migrate: true
#      enabled: true
#      driver-class-name: org.postgresql.Driver
#      locations: classpath:db/migration
#      schemas: member
#      url: jdbc:postgresql://localhost:5432/devpayflexdb
#      user: devpayflexuser
#      password: devpayflexpass









