server:
  port: 8081
spring:
  application:
    name: MEMBER-SERVICE  # This is the name of the service
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=member
    username: devpayflexuser
    password: devpayflexpass
    driver: postgres
    name: postgres
    pool:
      enabled: true
      max-size: 20
      initial-size: 1
      max-idle-time: 30m
      validation-query: SELECT 1
    data:
      r2dbc:
        repositories:
          enabled: true # Enable R2DBC repositories

  flyway:
    baseline-description: Baseline migration
    baseline-on-migrate: true
    enabled: true
    driver-class-name: org.postgresql.Driver
    locations: classpath:db/migration
    schemas: member
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: 1234

  #logging:
  #  level:
  #    sql: debug
  #    web: debug
  #    com:
  #      example: DEBUG
  #    name:
  #      postgres:
  #        r2dbc:
  #          migrate: Trace







